### PR TITLE
Document Dev Process 

### LINKED ISSUE #1: Document Git Branching approach
# PenCue Feature Request

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
using Vincent Driessen's [Git Branching Model](https://nvie.com/posts/a-successful-git-branching-model/) as starting point. Update for PenCue use.  All copyright for the original must be preserved. A reference to the original post must be include. 

**Additional context**
This should be a work in progress.

### PR DESCRIPTION
**Pull request by area42**
# PenCue Pull Request

### Scope
Document the Git Branching Model

### Related Issues

[Document Git Branching approach](https://github.com/PenCue/devprocess/issues/1)

### Types of changes

What types of changes are included in this PR? 
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Documentation Update (if none of the other choices apply)
- [ ] Includes an Architecture Decision Record(s) 
  - [ ] ADRs are team reviewed. 

### Checklist

- [ ] The PR is as small as it can be. Split if necessary 
- [ ] Lint and unit tests pass locally 
- [ ] Added tests that prove my fix is effective or that my feature works
- [x] Added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc..

### CODE REVIEW

**Comment by area42** [comment]
Can you review and give feedback. thanks.

**Review by jacco32 — COMMENTED** [review]
overall: nice!

some cosmetics I noticed while reading:

in README.md quick summary states:
- example given for branch naming doesn't follow the naming convention ;-)
- When you're finished, mark the PR for review by labelling with "Review & Merge".
  - I'm not seeing label "Review & Merge", should this be label "Ready"?

git-branching-model.md:
- "triggers and automatic" -> "triggers an automatic" ?
- " an Pull Request " ->  a Pull Request 
- completness -> completeness
- enviroments -> environments
- lowecase -> lowercase
- an medium -> a medium
- to high if starts ->  to high if it starts?
- Working an issue -> Working on an issue?

**Review by jacco32 — APPROVED** [review]

**Comment by area42** [comment]
I will create a new issue to fix cosmetics

**Comment by gvrutten** [comment]
Which version number are we going to use in the API? I assume only the major version? So /api/v1/person? This is a configuration parameter in Azure API Management

**Review by gvrutten — APPROVED** [review]

**Pull request merged**
